# Generated by Django 4.0.6 on 2022-08-16 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avian_app', '0002_alter_sighting_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sighting', to=settings.AUTH_USER_MODEL),
        ),
    ]
